### ISSUE TITLE
docker-compose run getting fail 

### ISSUE THREAD

**Issue by janaka120** [TomFern/dockerizing-nodejs#6]
Thank you for your "Dockerizing a Node.js Web Application" article.

When I try to run `docker-compose run addressbook npm run migrate`, I'm getting `ERROR: Service 'addressbook' failed to build : The command '/bin/sh -c useradd app' returned a non-zero code: 127`.

![Capture](https://user-images.githubusercontent.com/10891893/106647105-87b16280-65b4-11eb-856b-0621b6fb38b4.PNG)

I couldn't figure it out what was the problem. Do you have any idea? Please let me know.

**Comment by rainbow-kitty-42** [comment]
Try replace :
`RUN useradd app`
by :
```
RUN addgroup app
RUN adduser -S app
```

**Comment by TomFern** [comment]
Hi @janaka120 I'm sorry you're having trouble with the demo. The new version fixes this issue. Thank you @rainbow-kitty-42 for your suggestion, I've implemented it here. You can read the updated tutorial at:

https://semaphoreci.com/community/tutorials/dockerizing-a-node-js-web-application

Let me know if this fixes the issue for you.
